[project]
name = "caden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "chz>=0.4.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pandas>=3.0.0",
    "toml>=0.10.2",
    "tqdm>=4.66.3",
    "wandb>=0.24.1",
]

# Check at some point whether inspect uses a hf dependency which works w a more recent vllm
[project.optional-dependencies]
evals = [
    "inspect_evals[swe_bench]",
    "inspect_sandboxes",
    "modal>=1.3.4",
]
gpu = [
    "vllm>=0.11.0",
]

[tool.uv.sources]
inspect_evals = { path = "inspect_evals", editable = true }
inspect_sandboxes = { path = "inspect_sandboxes", editable = true }
